### PR TITLE
Add nested-object tests

### PR DESCRIPTION
**Pull request by WesTyler**
## Description
This PR provides failing tests against which to check template engine options.

## Related Issue

#1 

## Motivation and Context
Nested objects could not be used to hydrate templates.

## Types of changes

- [x] Testing only

## Checklist:
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dhinklexo — APPROVED** [review]

**Comment by WesTyler** [comment]
@dhinklexo @lamchakchan - I replaced doT with a small basic `Hoek.reach` parser. Will you guys take a peek to make sure there are no glaring issues? I tried to keep the logic small to meet exactly our templating needs and nothing more (for now).

**Comment by WesTyler** [comment]
Closes #2

**Comment by lamchakchan** [comment]
Do we need to evaluate expressions?  This will dictate if this is a feasible solution.

**Comment by WesTyler** [comment]
I don't _*think*_ so. At least we haven't needed to during development of toki-method-rabbit, toki-method-proxy, or toki-method-http so far.

**Comment by lamchakchan** [comment]
@WesTyler are we using Hoek for anything else than the `reach()` function?  If not, I would recommend just writing one yourself.  I wrote this in 10 minutes to proof out performance.

* Make something as fast as DoT
* Remove another dependency.

```
'use strict';

const data = {
    prop1 : {
        subprop1 : 'a',
        subprop2 : {
            hello : 'world'
        }
    }
}

const template = 'hello ${prop1.subprop2.hello}';

const reach = (key, data) => {

    const keys = key.split('.');
    let keyScope = keys.shift();
    let dataScope = data;
    let result = '';

    while (keyScope) {

        if(dataScope[keyScope]){
            dataScope = dataScope[keyScope];

            if (dataScope) { 
                keyScope = keys.shift();
                result = dataScope;
                }
        }
        else {
            keyScope = undefined;
            result = '';
        }
    }

    return typeof result === 'string' ? result : ''; 
}

const templater = (template, data) => {

    let result = [];
    let key = [];
    let isTemplate = false;

    for (let i = 0; i < template.length; ++i) {

        if (!isTemplate && template[i] === '$' && template[i+1] === '{') {
            i += 2;
            isTemplate = true;
        } 

        if (isTemplate && template[i] === '}') {
            ++i;
            isTemplate = false;
            result.push(reach(key.join(''), data));
            key = [];
        }

        if (isTemplate) {
            key.push(template[i]);
        }
        else {
            result.push(template[i]);
        }
    }

    return result.join('');
};

for (let i=0; i<1000; ++i) {
    templater(template, data);
}
```

**Comment by WesTyler** [comment]
No, that's the only thing we are using Hoek for. But Joi uses Hoek (pinned to the same version range as us), so we basically have it there already for free.

**Pull request merged**
